Домашнее задание №7
abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov pull request #12
Opened 2019-12-02 12:20 UTC by abdrakhimov1

Что сделано:

Добаил кнопку создания сообщения с геопозицией(нижний правый угол)
Добавил возможность drag'n'drop для загрузки картинок
Добавил отправку картинки на сервер
В планах сделать не просто отправку сообщения при переносе картинки, а создание превью над компоуз форм. Но по причине сжатых сроков сделал простую отправку.

Нужно добавить: отправку аудиосообщений(работаю над этим)

Прошу @priver , @martinkomitsky , @chexex проверить, что уже сделано.

2019-12-05 13:48 UTC, priver requested changes

2019-12-05 13:48 UTC, priver commented on src/components/Chat.js
> +					text:
не нужно хранить в стейте компоненты, можно сделать например поле type и нужные поля для сообщения (linkText, ...) в зависимости от типа.

2019-12-16 22:07 UTC, abdrakhimov1 commented
@priver, поправил замечание. Сорри, что так долго, закрывал зачеты.

2019-12-22 15:16 UTC, martinkomitsky commented
@priver

2019-12-23 11:03 UTC, priver requested changes

2019-12-23 11:03 UTC, priver commented on src/components/Chat.js
> +								<img src={imgToMessage} className='img_in_message' alt="img in message"/>,
а вот это?

2019-12-23 11:37 UTC, abdrakhimov1 commented on src/components/Chat.js
> +								<img src={imgToMessage} className='img_in_message' alt="img in message"/>,
Исправил

2019-12-23 15:36 UTC, priver approved these changes

2019-12-23 15:36 UTC, merged