Домашнее задание №10
abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov pull request #13
Opened 2019-12-23 11:45 UTC by abdrakhimov1

Домашнее задание №10

Что сделано:

1) Форма регистрации
2) Форма регистрации переводит по ссылке на мой бэк. Редиректом не получилось, выдавало ошибку 301. 
3) Работоспособность проверена на экзамене по бэку

Прошу @priver , @martinkomitsky , @chexex проверить домашнее задание.

2019-12-23 12:01 UTC, abdrakhimov1 commented
![Screenshot from 2019-12-23 15-00-15](https://user-images.githubusercontent.com/23650573/71357004-13288980-2595-11ea-8592-9fe39134dff5.png)

2019-12-23 15:38 UTC, priver requested changes
Ну а подчеркивания убрать? (text-decaration)

2019-12-23 22:31 UTC, abdrakhimov1 commented
![Screenshot from 2019-12-24 01-30-53](https://user-images.githubusercontent.com/23650573/71383376-1bacae80-25ed-11ea-8812-c1034cec9eba.png)

2019-12-23 22:33 UTC, abdrakhimov1 commented
Поправил

2019-12-30 10:44 UTC, priver approved these changes

2019-12-30 10:44 UTC, merged

2019-12-30 10:44 UTC, priver commented
6 баллов