Как убирать файлы из комита нормальным образом?
abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov pull request #3
Opened 2019-10-14 15:44 UTC by abdrakhimov1

У меня на компе всё работает, как сделать всё с git pages не понятно.

2019-10-14 15:52 UTC, abdrakhimov1 commented
Могу показать, как это выглядит на скринкасте или скриншотами. По чату телеграма, я так и не понял, как это нормально задеплоить на свой сайт

2019-10-14 23:11 UTC, abdrakhimov1 commented
Работает, неужели

https://abdrakhimov1.github.io/2019-2-Track-Frontend-D-Abdrakhimov/

2019-10-15 09:47 UTC, priver reviewed
что это вообще за PR?

2019-10-15 09:47 UTC, priver commented on web-components/src/components/Ad.js
> +        #user{
использовать классы для селекторов

2019-10-15 09:47 UTC, priver commented on web-components/src/components/Message.js
> +  JsonMaker(messageNumber) {
это нигде не вызывается, записи в localStorage нет

2019-10-15 09:47 UTC, priver commented on web-components/src/components/Messanger.js
> +    this.$message_field = this.shadowRoot.querySelector('ad-form');
перезаписываем поле

2019-10-15 09:47 UTC, priver commented on web-components/src/components/Ad.js
> +    this.$name.textContent = 'Реклама для Mail.ru';
что это вообще?

2019-10-15 09:47 UTC, priver commented on web-components/src/components/FriendListForm.js
> +    <list-unit></list-unit>
???

2019-10-15 12:38 UTC, abdrakhimov1 commented on web-components/src/components/FriendListForm.js
> +    <list-unit></list-unit>
Это для 3го дз.

2019-10-15 12:38 UTC, abdrakhimov1 commented on web-components/src/components/Ad.js
> +    this.$name.textContent = 'Реклама для Mail.ru';
Удалил

2019-10-15 12:41 UTC, priver commented on web-components/src/components/FriendListForm.js
> +    <list-unit></list-unit>
сделай, пожалуйста, PR для второго ДЗ.
добавь описание и все остальное согласно требованиям.
в таком виде принимать PR я у тебя не буду

2019-10-15 12:54 UTC, abdrakhimov1 reviewed
Удалил лишнее

2019-10-15 12:58 UTC, abdrakhimov1 commented on web-components/src/components/Message.js
> +  JsonMaker(messageNumber) {
Сейчас пофикшу

2019-10-15 13:07 UTC, abdrakhimov1 reviewed
Как же трудно

2019-10-15 16:19 UTC, abdrakhimov1 reviewed
# Домашнее задание №2

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:

1) Форма чата
2) Различные формы для компонентов окна чата. 
3) Расположение компонентов согласно макету
4) Конвертация сообщения в json и добавление json-файлов в localStorage
5) Доступ и выгрузка json файлов из localStorage с сохранением порядка добавления сообщений в чат

2019-10-15 18:34 UTC, priver requested changes

2019-10-15 18:34 UTC, priver commented on web-components/src/components/FormInput.js
> +        <img src ="https://icon-icons.com/icons2/1863/PNG/48/description_119232.png"  height:50px;" style = "margin-left : 20px;">
height должно быть внутри style

2019-10-15 18:34 UTC, priver commented on web-components/src/components/MessageField.js
> +      for (let i = 0; i < localStorage.messageNumber; i++) {
нужно сохранять сообщения в массив и записать его целиком в localStorage

2019-10-15 18:34 UTC, priver commented on web-components/src/components/MessageField.js
> +        if (workingJson.user === 'Danny') {
кто такой Danny?

2019-10-15 20:46 UTC, abdrakhimov1 commented on web-components/src/components/MessageField.js
> +        if (workingJson.user === 'Danny') {
Исправил на User

2019-10-15 20:51 UTC, abdrakhimov1 commented on web-components/src/components/FormInput.js
> +        <img src ="https://icon-icons.com/icons2/1863/PNG/48/description_119232.png"  height:50px;" style = "margin-left : 20px;">
Вынес весь стиль иконок в template

2019-10-17 10:31 UTC, priver approved these changes
Отлично, 12 баллов

2019-10-17 10:31 UTC, merged