Домашнее задание 3 и 4
abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov pull request #4
Opened 2019-10-23 09:09 UTC by abdrakhimov1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:

Созданы элементы: кнопка, список чатов, элемент списка чатов
Созданы анимации на конпку при наведении и нажатии
Добавлена анимация при наведении на элемент списка чатов
Добавлен onclick при нажатии на кнопку(создана функция в которую можно добавить логику добавления чата)

2019-10-24 07:15 UTC, martinkomitsky requested changes
Плохо, что сделал 2 домашки в 1 ветке. В следующий раз нужно разделять по одной ветке.

Сейчас нужно разложить дз на gh-pages. Добавь ветку в https://github.com/abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov/blob/master/.travis.yml

2019-10-25 04:14 UTC, martinkomitsky requested changes
Не совсем уверен, что понял, как правильно пользоваться приложением.
![image](https://user-images.githubusercontent.com/14847018/67542713-bb85b300-f6f6-11e9-9508-33fe55096a03.png)
1. Нет перехода в сам чат (или я не нашел. Я пытался, честно)
2. В названии файлика `Messanger` допущена ошибка
3. Иконки/картинки с внешнего ресурса типа https://icon-icons.com/icons2/1904/PNG/128/menu_121304.png отдают 403. На скриншоте это видно
4. Есть js ошибка при нажатии на "new message". Тоже видно на скриншоте

2019-10-26 10:22 UTC, abdrakhimov1 commented
1. Поправил переход в чат. Теперь можно входить в чат и выходить обратно в список чатов через стрелочку.
2. Поправил иконки 
3. Не понимаю, почему появляется ошибка при нажатии на кнопку. Ошибка в функции в AddChat в Messenger.js

2019-10-26 12:18 UTC, martinkomitsky commented
> * Поправил переход в чат. Теперь можно входить в чат и выходить обратно в список чатов через стрелочку.
Действительно, теперь работает.
> * Поправил иконки
У меня они по прежнему 403 отдают. Ладно, черт с ним
> * Не понимаю, почему появляется ошибка при нажатии на кнопку. Ошибка в функции в AddChat в Messenger.js
Ниже скриншот с причиной ошибки. Ее надо исправить

![image](https://user-images.githubusercontent.com/14847018/67619379-b4000000-f803-11e9-86ef-ab8bdb930180.png)

2019-10-26 12:29 UTC, abdrakhimov1 commented
Как поправить 403 ошибку? Если загружать картинки с локальной папки, ругается на доступ. А если вставлять ссылки на картинки, то высвечиваются только у меня.
Я понимаю, где ошибка, не понимаю, почему не работает getElementById в shadowdom, хотя он там есть

2019-10-26 12:47 UTC, martinkomitsky commented
> Как поправить 403 ошибку? Если загружать картинки с локальной папки, ругается на доступ. А если вставлять ссылки на картинки, то высвечиваются только у меня.

Ты можешь скачать эти картинки по ссылкам к себе в `/images/`, а чтобы они показывались не только у тебя, можешь донастроить `webpack`, как мы это показывали на семинаре (https://webpack.js.org/plugins/copy-webpack-plugin/)
Нужно скопировать эти файлы в build в момент сборки

>Я понимаю, где ошибка, не понимаю, почему не работает getElementById в shadowdom, хотя он там есть

Твой элемент `=== null`, поэтому возникает ошибка

2019-10-27 09:50 UTC, abdrakhimov1 commented
1. Пофиксил картинки. Теперь загружаются из build.
2. Пофиксил ошибку с добавлением нового чата.
3. Добавил анимацию увеличения при наведении на все иконки.

2019-10-27 11:37 UTC, martinkomitsky approved these changes
Супер, спасибо за картинкосы!

6 за 3.
12 за 4.

Впредь, пожалуйста, делай дз в разных ветках.

2019-10-27 11:37 UTC, merged