Домашнее задание №6
abdrakhimov1/2019-2-Track-Frontend-D-Abdrakhimov pull request #8
Opened 2019-11-21 22:15 UTC by abdrakhimov1

1) Сделал страницу профиля
2) Добавил иконку для перехода на страницу профиля на главную страницу
3) Настроил руты
прошу  @martinkomitsky , @chexex  и  @priver  проверить дз.

2019-11-23 11:44 UTC, martinkomitsky commented on src/components/style_css/Compose.css
> +  -o-transform: scale(1.1);
убрать префиксы!!! везде!

2019-11-23 11:47 UTC, martinkomitsky requested changes
1. Убрать префиксы для стилей и оставить стандартные свойства.
2. Сделать так, чтобы каждый чат сохранялся и для конкретного чата был адрес типа `/chats/1`, `/chats/2` и т.д.. Сейчас я вижу, что открывается всегда один чат, а сообщения не сохраняются

2019-11-25 23:10 UTC, abdrakhimov1 commented
Исправил все замечания

2019-11-27 04:22 UTC, martinkomitsky requested changes
Спасибо! уже гораздо лучше. Но заметил, что почему-то нет некоторых вещей из старых дз:
1. Не работает доскролл вниз при написании нового сообщения
2. Нет анимации появления новых сообщений
3. Последние сообщения не показываются на списке чатов

Если получится исправить, не буду обращать внимание на просрочку и поставлю макс

2019-11-27 20:59 UTC, abdrakhimov1 commented
Исправил все замечания. Чтобы создать новый чат воспользуйтесь кнопкой "+" в правом верхнем углу.

2019-11-28 03:41 UTC, martinkomitsky approved these changes
ура, 12

2019-11-28 03:42 UTC, merged